### PR TITLE
the proposed complete template

### PR DESCRIPTION
**Pull request by princeadeyeye**
A complete template 

pull the branch
fetch the branch 
npm install for dependencies
npm start

### CODE REVIEW

**Review by OluwmayowaF — COMMENTED** [review]
Please are we certain this won't conflict with the existing installed template? @vicradon @princeadeyeye .. I just a confirmation before i approve

**Comment by OluwmayowaF** [comment]
@vicradon what is the status of your review on this?

**Comment by vicradon** [comment]
We are checking sha

The default has too many errors

**Review by vicradon — COMMENTED** [review]
This is dated

**Pull request closed without merging**
